DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auth_user') THEN
    GRANT USAGE ON SCHEMA public TO auth_user;

    GRANT SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA public
      TO auth_user;

    GRANT USAGE, SELECT, UPDATE
      ON ALL SEQUENCES IN SCHEMA public
      TO auth_user;

    GRANT EXECUTE
      ON ALL FUNCTIONS IN SCHEMA public
      TO auth_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO auth_user;
  END IF;
END
$$;
