DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auth_user') THEN
    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      REVOKE EXECUTE ON FUNCTIONS FROM auth_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      REVOKE USAGE, SELECT, UPDATE ON SEQUENCES FROM auth_user;

    ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
      REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM auth_user;

    REVOKE EXECUTE
      ON ALL FUNCTIONS IN SCHEMA public
      FROM auth_user;

    REVOKE USAGE, SELECT, UPDATE
      ON ALL SEQUENCES IN SCHEMA public
      FROM auth_user;

    REVOKE SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA public
      FROM auth_user;

    REVOKE USAGE ON SCHEMA public FROM auth_user;
  END IF;
END
$$;
