service_name: auth-service
env: docker
version: dev

log_level: info
shutdown_timeout: 10s

token_ttl: 1h
refresh_ttl: 168h

grpc:
  port: 44044
  timeout: 5s

http:
  port: 8082
  timeout: 5s

otlp:
  endpoint: jaeger:4317

postgres:
  host: postgres-haproxy
  port: 5432
  db_name: authdb
  user: auth_user
  password: auth_password
  ssl_mode: disable


tls:
  enabled: true
  cert_file: /app/certs/auth-service.crt
  key_file: /app/certs/auth-service.key
  ca_file: /app/certs/ca.crt
  client_ca_file: /app/certs/ca.crt
  require_client_cert: true

