service_name: auth-service
env: docker
version: dev

log_level: info
shutdown_timeout: 10s

token_ttl: 1h
refresh_ttl: 168h

grpc:
  port: 44044
  timeout: 5s

http:
  port: 8082
  timeout: 5s

otlp:
  endpoint: jaeger:4317

postgres:
  host: auth-postgres
  port: 5432
  db_name: authdb
  user: postgres
  password: postgres
  ssl_mode: disable
